// --------------------------------------------------------------------------------
// Copyright AspDotNetStorefront.com. All Rights Reserved.
// http://www.aspdotnetstorefront.com
// For details on this license please visit the product homepage at the URL above.
// THE ABOVE NOTICE MUST REMAIN INTACT. 
// --------------------------------------------------------------------------------
/* 
 * Signifyd API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;

namespace AspDotNetStorefront.Signifyd.Client
{
	/// <summary>
	/// API Response
	/// </summary>
	public class ApiResponse<T>
	{
		/// <summary>
		/// Gets or sets the status code (HTTP status code)
		/// </summary>
		/// <value>The status code.</value>
		public int StatusCode { get; private set; }

		/// <summary>
		/// Gets or sets the HTTP headers
		/// </summary>
		/// <value>HTTP headers</value>
		public IDictionary<string, string> Headers { get; private set; }

		/// <summary>
		/// Gets or sets the data (parsed HTTP body)
		/// </summary>
		/// <value>The data.</value>
		public T Data { get; private set; }

		/// <summary>
		/// Initializes a new instance of the <see cref="ApiResponse&lt;T&gt;" /> class.
		/// </summary>
		/// <param name="statusCode">HTTP status code.</param>
		/// <param name="headers">HTTP headers.</param>
		/// <param name="data">Data (parsed HTTP body)</param>
		public ApiResponse(int statusCode, IDictionary<string, string> headers, T data)
		{
			this.StatusCode = statusCode;
			this.Headers = headers;
			this.Data = data;
		}

	}

}
