// --------------------------------------------------------------------------------
// Copyright AspDotNetStorefront.com. All Rights Reserved.
// http://www.aspdotnetstorefront.com
// For details on this license please visit the product homepage at the URL above.
// THE ABOVE NOTICE MUST REMAIN INTACT. 
// --------------------------------------------------------------------------------
namespace AspDotNetStorefront.Routing
{
	public static class ActionNames
	{
		public static readonly string Accept = "Accept";
		public static readonly string Account = "Account";
		public static readonly string AddGiftCard = "AddGiftCard";
		public static readonly string AddPromoCode = "AddPromoCode";
		public static readonly string AddToCart = "AddToCart";
		public static readonly string AddToCartForm = "AddToCartForm";
		public static readonly string AdvancedSearch = "AdvancedSearch";
		public static readonly string AjaxAddToCart = "AjaxAddToCart";
		public static readonly string AjaxAddKitToCart = "AjaxAddKitToCart";
		public static readonly string AjaxGetKitData = "AjaxGetKitData";
		public static readonly string AlternativePaymentMethods = "AlternativePaymentMethods";
		public static readonly string AmazonPayments = "AmazonPayments";
		public static readonly string AmazonPaymentsCallback = "AmazonPaymentsCallback";
		public static readonly string AmazonPaymentsComplete = "AmazonPaymentsComplete";
		public static readonly string AmazonPaymentsDetail = "AmazonPaymentsDetail";
		public static readonly string AcceptJsCreditCard = nameof(AcceptJsCreditCard);
		public static readonly string AcceptJsECheck = nameof(AcceptJsECheck);
		public static readonly string AuthorizeNetSilentPost = "AuthorizeNetSilentPost";
		public static readonly string BraintreeCreditCard = "BraintreeCreditCard";
		public static readonly string BraintreeThreeDSecureFail = "BraintreeThreeDSecureFail";
		public static readonly string BraintreeThreeDSecurePass = "BraintreeThreeDSecurePass";
		public static readonly string BulkAddToCart = "BulkAddToCart";
		public static readonly string BulkAddToCartForm = "BulkAddToCartForm";
		public static readonly string BuySafeGuarantee = "BuySafeGuarantee";
		public static readonly string Callback = "Callback";
		public static readonly string ChangeCountry = "ChangeCountry";
		public static readonly string ChangePassword = "ChangePassword";
		public static readonly string CheckoutCart = "CheckoutCart";
		public static readonly string ClearShippingEstimate = "ClearShippingEstimate";
		public static readonly string Confirmation = "Confirmation";
		public static readonly string Create = "Create";
		public static readonly string CreateAccount = "CreateAccount";
		public static readonly string CreditCard = "CreditCard";
		public static readonly string CreditCardDetail = "CreditCardDetail";
		public static readonly string ECheck = nameof(ECheck);
		public static readonly string ECheckDetail = nameof(ECheckDetail);
		public static readonly string DebugRealTimeShipping = "DebugRealTimeShipping";
		public static readonly string Decline = "Decline";
		public static readonly string Delete = "Delete";
		public static readonly string DeleteItem = "DeleteItem";
		public static readonly string DeleteMinicartItem = "DeleteMinicartItem";
		public static readonly string Detail = "Detail";
		public static readonly string Download = "Download";
		public static readonly string Edit = "Edit";
		public static readonly string EmailProduct = "EmailProduct";
		public static readonly string EndPreview = "EndPreview";
		public static readonly string Entity = "Entity";
		public static readonly string Error = "Error";
		public static readonly string GiftCardSetup = "GiftCardSetup";
		public static readonly string GoogleCustomerReviewsBadge = "GoogleCustomerReviewsBadge";
		public static readonly string GoogleCustomerReviewsOptInSurvey = "GoogleCustomerReviewsOptInSurvey";
		public static readonly string Index = "Index";
		public static readonly string KitAddToCart = "KitAddToCart";
		public static readonly string KitAddToCartForm = "KitAddToCartForm";
		public static readonly string List = "List";
		public static readonly string LoginLinks = "LoginLinks";
		public static readonly string MakePrimaryAddress = "MakePrimaryAddress";
		public static readonly string MicroPayDetail = "MicroPayDetail";
		public static readonly string MinicartLink = "MinicartLink";
		public static readonly string MinicartResources = "MinicartResources";
		public static readonly string MoveItemToCart = "MoveItemToCart";
		public static readonly string MoveAllToCart = "MoveAllToCart";
		public static readonly string NotFound = "NotFound";
		public static readonly string Notify = "Notify";
		public static readonly string Ok = "Ok";
		public static readonly string OrderOption = "OrderOption";
		public static readonly string OrderNotes = "OrderNotes";
		public static readonly string OrderSummary = "OrderSummary";
		public static readonly string PaymentMethod = "PaymentMethod";
		public static readonly string PayPalExpressReturn = "PayPalExpressReturn";
		public static readonly string PlaceOrder = "PlaceOrder";
		public static readonly string PopUp = "PopUp";
		public static readonly string PostalCodeLookup = "PostalCodeLookup";
		public static readonly string PostalCodeRegexMap = "PostalCodeRegexMap";
		public static readonly string PreviewBar = "PreviewBar";
		public static readonly string PurchaseOrder = "PurchaseOrder";
		public static readonly string PurchaseOrderDetail = "PurchaseOrderDetail";
		public static readonly string RateProduct = "RateProduct";
		public static readonly string RateComment = "RateComment";
		public static readonly string Receipt = "Receipt";
		public static readonly string RefreshSession = "RefreshSession";
		public static readonly string RemovePromo = "RemovePromo";
		public static readonly string Remove = "Remove";
		public static readonly string RemoveGiftCard = "RemoveGiftCard";
		public static readonly string ReOrder = "ReOrder";
		public static readonly string ResetPassword = "ResetPassword";
		public static readonly string SagePayPiCreditCard = "SagePayPiCreditCard";
		public static readonly string SagePayPiThreeDSecureFail = "SagePayPiThreeDSecureFail";
		public static readonly string SagePayPiPaRes = "SagePayPiPaRes";
		public static readonly string SagePayPiThreeDSecurePass = "SagePayPiThreeDSecurePass";
		public static readonly string SelectAddress = "SelectAddress";
		public static readonly string SelectWallet = "SelectWallet";
		public static readonly string SetCurrency = "SetCurrency";
		public static readonly string SetEmail = "SetEmail";
		public static readonly string SetLocale = "SetLocale";
		public static readonly string SetVatSetting = "SetVatSetting";
		public static readonly string SetPaymentMethod = "SetPaymentMethod";
		public static readonly string ShippingEstimate = "ShippingEstimate";
		public static readonly string ShippingMethod = "ShippingMethod";
		public static readonly string ShoppingCartUpsells = "ShoppingCartUpsells";
		public static readonly string SignIn = "SignIn";
		public static readonly string SignOut = "SignOut";
		public static readonly string SimpleAddToCartForm = "SimpleAddToCartForm";
		public static readonly string StartPayPalExpress = "StartPayPalExpress";
		public static readonly string States = "States";
		public static readonly string ThreeDSecure = "ThreeDSecure";
		public static readonly string ThreeDSecureForm = "ThreeDSecureForm";
		public static readonly string ThreeDSecureReturn = "ThreeDSecureReturn";
		public static readonly string Topics = "Topics";
		public static readonly string TwoCheckout = "TwoCheckout";
		public static readonly string TwoCheckoutReturn = "TwoCheckoutReturn";
		public static readonly string UpdateMinicart = "UpdateMinicart";
		public static readonly string UpdateOkToEmail = "UpdateOkToEmail";
		public static readonly string UpdateOver13 = "UpdateOver13";
		public static readonly string UpdateTermsAndConditions = "UpdateTermsAndConditions";
		public static readonly string Webhook = "Webhook";
	}
}
