// --------------------------------------------------------------------------------
// Copyright AspDotNetStorefront.com. All Rights Reserved.
// http://www.aspdotnetstorefront.com
// For details on this license please visit the product homepage at the URL above.
// THE ABOVE NOTICE MUST REMAIN INTACT. 
// --------------------------------------------------------------------------------
/* 
 * Signifyd API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AspDotNetStorefront.Signifyd.Client.SwaggerDateConverter;

namespace AspDotNetStorefront.Signifyd.Model
{
    /// <summary>
    /// Defines ShippingMethod
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ShippingMethod
    {
        
        /// <summary>
        /// Enum CRITICAL for "CRITICAL"
        /// </summary>
        [EnumMember(Value = "CRITICAL")]
        CRITICAL,
        
        /// <summary>
        /// Enum EXPRESS for "EXPRESS"
        /// </summary>
        [EnumMember(Value = "EXPRESS")]
        EXPRESS,
        
        /// <summary>
        /// Enum FIRSTCLASS for "FIRST_CLASS"
        /// </summary>
        [EnumMember(Value = "FIRST_CLASS")]
        FIRSTCLASS,
        
        /// <summary>
        /// Enum FIRSTCLASSINTERNATIONAL for "FIRST_CLASS_INTERNATIONAL"
        /// </summary>
        [EnumMember(Value = "FIRST_CLASS_INTERNATIONAL")]
        FIRSTCLASSINTERNATIONAL,
        
        /// <summary>
        /// Enum FREE for "FREE"
        /// </summary>
        [EnumMember(Value = "FREE")]
        FREE,
        
        /// <summary>
        /// Enum FREIGHT for "FREIGHT"
        /// </summary>
        [EnumMember(Value = "FREIGHT")]
        FREIGHT,
        
        /// <summary>
        /// Enum GROUND for "GROUND"
        /// </summary>
        [EnumMember(Value = "GROUND")]
        GROUND,
        
        /// <summary>
        /// Enum INTERNATIONAL for "INTERNATIONAL"
        /// </summary>
        [EnumMember(Value = "INTERNATIONAL")]
        INTERNATIONAL,
        
        /// <summary>
        /// Enum OVERNIGHT for "OVERNIGHT"
        /// </summary>
        [EnumMember(Value = "OVERNIGHT")]
        OVERNIGHT,
        
        /// <summary>
        /// Enum PRIORITY for "PRIORITY"
        /// </summary>
        [EnumMember(Value = "PRIORITY")]
        PRIORITY,
        
        /// <summary>
        /// Enum PRIORITYINTERNATIONAL for "PRIORITY_INTERNATIONAL"
        /// </summary>
        [EnumMember(Value = "PRIORITY_INTERNATIONAL")]
        PRIORITYINTERNATIONAL,
        
        /// <summary>
        /// Enum STANDARD for "STANDARD"
        /// </summary>
        [EnumMember(Value = "STANDARD")]
        STANDARD,
        
        /// <summary>
        /// Enum THREEDAY for "THREE_DAY"
        /// </summary>
        [EnumMember(Value = "THREE_DAY")]
        THREEDAY,
        
        /// <summary>
        /// Enum TWODAY for "TWO_DAY"
        /// </summary>
        [EnumMember(Value = "TWO_DAY")]
        TWODAY,
        
        /// <summary>
        /// Enum TWODAYMORNING for "TWO_DAY_MORNING"
        /// </summary>
        [EnumMember(Value = "TWO_DAY_MORNING")]
        TWODAYMORNING
    }

}
